# Generated by Django 4.0.4 on 2022-05-17 09:37

import csvapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0002_alter_customer_password_alter_customer_password1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(upload_to=csvapp.models.Product.nameFile),
        ),
    ]
